Better error exit strategy

diff --git a/commands/git-finish b/commands/git-finish
--- a/commands/git-finish
+++ b/commands/git-finish
@@ -14,6 +14,9 @@
 #
 ##
 
+# exit on error
+set -e
+
 BRANCH=$(git rev-parse --abbrev-ref HEAD)
 TYPE=$1
 
@@ -23,11 +26,11 @@ if [[ $BRANCH = 'master' || $BRANCH = 'develop' ]]; then
 fi
 
 if [[ $TYPE = 'hotfix' || ${BRANCH:0:7} = "hotfix/" ]]; then
-  git checkout master || exit 255
-  git merge --no-ff $BRANCH || exit 255
+  git checkout master
+  git merge --no-ff $BRANCH
   [[ $1 = 'push' || $2 = 'push' ]] && git push origin master
 fi
 
-git checkout develop || exit 255
-git merge --no-ff $BRANCH || exit 255
+git checkout develop
+git merge --no-ff $BRANCH
 [[ $1 = 'push' || $2 = 'push' ]] && git push origin develop
diff --git a/commands/git-start b/commands/git-start
--- a/commands/git-start
+++ b/commands/git-start
@@ -14,6 +14,9 @@
 #
 ##
 
+# exit on error
+set -e
+
 if [[ $1 = '' || $2 = '' ]]; then
   echo "Please specify a type (ie hotfix) and name (ie FAD-1234)"
   exit 255
